# Generated by Django 4.2.28 on 2026-02-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('kitchen', 'Kitchen Staff')], default='waiter', max_length=20),
        ),
    ]
