# Generated by Django 4.2.28 on 2026-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Waiter', 'Waiter'), ('Kitchen Staff', 'Kitchen Staff')], default='Waiter', max_length=50),
        ),
    ]
