# Generated by Django 4.2.28 on 2026-02-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_order_remove_menuitem_is_available_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(choices=[(1, 'Table 1'), (2, 'Table 2'), (3, 'Table 3'), (4, 'Table 4'), (5, 'Table 5')]),
        ),
    ]
