# Generated by Django 4.2.28 on 2026-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
