# Generated by Django 4.2.28 on 2026-04-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
            ],
            options={
                'verbose_name': 'Billing & Payment',
                'verbose_name_plural': 'Billing & Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_panel.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
