# Generated by Django 4.2.28 on 2026-08-17 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "admin_panel",
            "0019_order_is_paid_order_ref_id_order_transaction_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.IntegerField(
                choices=[
                    (1, "Table 1"),
                    (2, "Table 2"),
                    (3, "Table 3"),
                    (4, "Table 4"),
                    (5, "Table 5"),
                    (6, "Table 6"),
                    (7, "Table 7"),
                    (8, "Table 8"),
                    (9, "Table 9"),
                    (10, "Table 10"),
                    (11, "Table 11"),
                    (12, "Table 12"),
                    (13, "Table 13"),
                    (14, "Table 14"),
                    (15, "Table 15"),
                    (16, "Table 16"),
                    (17, "Table 17"),
                    (18, "Table 18"),
                    (19, "Table 19"),
                    (20, "Table 20"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("vat_number", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_cafe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="cafe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="admin_panel.cafe",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cafe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="admin_panel.cafe",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cafe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="admin_panel.cafe",
            ),
        ),
    ]
